# see example at https://gist.github.com/jhass/a5ae80d87f18e53e7b56

inherit_from:
  <%= ENV['IGNORE_RUBOCOP_TODO'] ? "# - .rubocop_todo.yml" : "- .rubocop_todo.yml" %>
  - .rubocop-minitest.yml

plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.2
  # TargetRailsVersion: 7.2.2
  # Exclude:
  #   - 'Gemfile.lock'

Naming/VariableNumber:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false
  EnforcedStyle: final_blank_line

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Naming/MethodParameterName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/ParameterLists:
  Enabled: false 