require_relative 'api/client'
require_relative 'api/namespace/saved_object'
require_relative 'api/namespace/dashboard'
require_relative 'api/namespace/index_pattern'
require_relative 'api/namespace/space'
require_relative 'api/namespace/user'
require_relative 'api/namespace/visualization'
